tunnel: mordum-loan-tunnel
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # SSH Access - sshroster.mordum.loan
  - hostname: sshroster.mordum.loan
    service: tcp://localhost:22
  
  # Roster Data API - Prioridad alta (debe estar primero)
  - hostname: roster.mordum.loan
    service: http://localhost:3000
  
  # Raid Groups - raids.mordum.loan
  - hostname: raids.mordum.loan
    service: http://localhost:3001
  
  # Catch-all rule - debe estar al final
  - service: http_status:404

